### ISSUE TITLE
Bug: | MissingPropertyError > core | A required property is missing

### ISSUE THREAD

**Issue by KrazyKleb** [diced/zipline#515]
### What happened?

Look at logs

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
| MissingPropertyError > core
  |   A required property is missing

   Collecting page data  ..2023-12-18 12:38:08,015 AM error [config] Config is invalid, see below:
2023-12-18 12:38:08,017 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  ...2023-12-18 12:38:08,251 AM error [config] Config is invalid, see below:
2023-12-18 12:38:08,257 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

2023-12-18 12:38:08,269 AM error [config] Config is invalid, see below:
2023-12-18 12:38:08,271 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  .2023-12-18 12:38:08,374 AM error [config] Config is invalid, see below:
2023-12-18 12:38:08,375 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

2023-12-18 12:38:08,428 AM error [config] Config is invalid, see below:
2023-12-18 12:38:08,430 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  ..2023-12-18 12:38:09,811 AM error [config] Config is invalid, see below:
2023-12-18 12:38:09,813 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  ...2023-12-18 12:38:10,019 AM error [config] Config is invalid, see below:
2023-12-18 12:38:10,021 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

2023-12-18 12:38:10,059 AM error [config] Config is invalid, see below:
2023-12-18 12:38:10,071 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

2023-12-18 12:38:10,131 AM error [config] Config is invalid, see below:
2023-12-18 12:38:10,143 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  .2023-12-18 12:38:10,308 AM error [config] Config is invalid, see below:
2023-12-18 12:38:10,310 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  ..2023-12-18 12:38:10,473 AM error [config] Config is invalid, see below:
2023-12-18 12:38:10,476 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  ..2023-12-18 12:38:11,137 AM error [config] Config is invalid, see below:
2023-12-18 12:38:11,141 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  ...2023-12-18 12:38:11,235 AM error [config] Config is invalid, see below:
2023-12-18 12:38:11,237 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  ...2023-12-18 12:38:11,880 AM error [config] Config is invalid, see below:
2023-12-18 12:38:11,882 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

2023-12-18 12:38:11,951 AM error [config] Config is invalid, see below:
2023-12-18 12:38:11,954 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

2023-12-18 12:38:11,969 AM error [config] Config is invalid, see below:
2023-12-18 12:38:11,973 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing

   Collecting page data  .2023-12-18 12:38:12,704 AM error [config] Config is invalid, see below:
2023-12-18 12:38:12,719 AM error [config] CombinedPropertyError (1)
  Received one or more errors

  input.core
  | MissingPropertyError > core
  |   A required property is missing


> Build error occurred
Error: Jest worker encountered 4 child process exceptions, exceeding retry limit
    at ChildProcessWorker.initialize (/home/container/node_modules/next/dist/compiled/jest-worker/index.js:1:11580)
    at ChildProcessWorker._onExit (/home/container/node_modules/next/dist/compiled/jest-worker/index.js:1:12545)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  type: 'WorkerError'
}
   Collecting page data  .ERROR: "build:next" exited with 1.
```

**Comment by livingflore** [comment]
+1, WSL 5.10.102.1 Ubuntu 20.04 LTS

**Comment by livingflore** [comment]
> It could be that you haven't set your config with a `.env.local` from `.env.local.example` if you have the original error when starting.

https://github.com/diced/zipline/issues/404#issuecomment-1546767837

**Comment by diced** [comment]
Are you sure that it contains the necessary variables: `CORE_SECRET` and `CORE_DATABASE_URL`?

**Comment by KrazyKleb** [comment]
> Are you sure that it contains the necessary variables: `CORE_SECRET` and `CORE_DATABASE_URL`?

Yes

**Comment by KrazyKleb** [comment]
CORE_RETURN_HTTPS=true
CORE_SECRET="actual secret"
CORE_HOST=real hostname.com
CORE_PORT=REAL PORT
CORE_DATABASE_URL="postgresql://postgres:password@db.REALDBURL.supabase.co"
CORE_LOGGER=false
CORE_STATS_INTERVAL=1800
CORE_INVITES_INTERVAL=1800
CORE_THUMBNAILS_INTERVAL=600

If you want the full file let me know

**Comment by KrazyKleb** [comment]
I fixed the issue by deleting the files and recreating them.
