### ISSUE TITLE
Bug: Database Error

### ISSUE THREAD

**Issue by KrazyKleb** [diced/zipline#516]
### What happened?

A bug happened!
Look at the logs

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

```shell
Migration name: 20210901024501_embed_image
Database error code: 42P01
Database error:
ERROR: relation "Image" does not exist
DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"Image\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("namespace.c"), line: Some(433), routine: Some("RangeVarGetRelidExtended") }

    at Object.<anonymous> (/home/container/node_modules/@prisma/migrate/dist/SchemaEngine.js:415:24)
    at SchemaEngine.handleResponse (/home/container/node_modules/@prisma/migrate/dist/SchemaEngine.js:256:36)
    at LineStream.<anonymous> (/home/container/node_modules/@prisma/migrate/dist/SchemaEngine.js:363:16)
    at LineStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream._pushBuffer (/home/container/node_modules/@prisma/migrate/dist/utils/byline.js:103:17)
    at LineStream._transform (/home/container/node_modules/@prisma/migrate/dist/utils/byline.js:97:8)
    at Transform._write (node:internal/streams/transform:175:8)
```

### Additional Info

I'm using a custom pterodactyl egg (https://github.com/DanBot-Hosting/pterodactyl-eggs/blob/main/egg-a-i-o.json)

**Comment by KrazyKleb** [comment]
@diced

**Comment by TacticalTechJay** [comment]
Gonna need a bit more context. Was this a failed migration?

**Comment by KrazyKleb** [comment]
> Gonna need a bit more context. Was this a failed migration? Any debug logs?

How do I get debug logs?

**Comment by TacticalTechJay** [comment]
> > Gonna need a bit more context. Was this a failed migration? Any debug logs?
> 
> How do I get debug logs?

You add `DEBUG=true` to the env variables.

**Comment by KrazyKleb** [comment]
yarn start
2023-12-23 12:43:52,283 PM debug [config] Unable to parse UPLOADER_ADMIN_LIMIT=104900000
2023-12-23 12:43:52,285 PM debug [config] Unable to parse UPLOADER_USER_LIMIT=104900000
2023-12-23 12:43:52,286 PM debug [config] Attemping to validate {"core":{"return_https":tr","logger":true,"stats_interval":1800,"invites_interval":1800,"thumbnails_interval":600},"datasource":{"type":"supabase","supabase":{"url":"https:/.supabase.co","key":"","bucket":"zipline"}},"uploader":{"default_format":"RANDOM","route":"/u","length":6,"disabled_extensions":["someext","anotherext"]},"urls":{"route":"/go","length":6},"ratelimit":{"user":5,"admin":3}}
2023-12-23 12:43:52,289 PM debug [config] Recieved config: {"core":{"enabled":false,"on_dashboard":false}},"datasource":{"type":"supabase","local":{"directory":"./uploads"},"supabase":{"url":"https://z.supabase.co","key":"","bucket":"zipline"}},"uploader":{"default_format":"RANDOM","route":"/u","embed_route":"/a","length":6,"admin_limit":104857600,"user_limit":104857600,"disabled_extensions":["someext","anotherext"],"format_date":"YYYY-MM-DD_HH:mm:ss","default_expiration":null,"assume_mimetypes":false,"random_words_separator":"-"},"urls":{"route":"/go","length":6},"ratelimit":{"user":5,"admin":3},"website":{"title":"Zipline","show_files_per_user":true,"show_version":true,"disable_media_preview":false,"external_links":[{"label":"Zipline","link":"https://github.com/diced/zipline"},{"label":"Documentation","link":"https://zipline.diced.sh/"}]},"discord":null,"oauth":null,"features":{"invites":false,"invites_length":6,"oauth_registration":false,"oauth_login_only":false,"user_registration":false,"headless":false,"default_avatar":null,"robots_txt":false,"thumbnails":false},"chunks":{"max_size":94371840,"chunks_size":20971520,"enabled":true},"mfa":{"totp_issuer":"Zipline","totp_enabled":false},"exif":{"enabled":false,"remove_gps":false},"ssl":null}
2023-12-23 12:43:52,289 PM info  [datasource] using Supabase(zipline) datasource
2023-12-23 12:43:52,313 PM debug [server] Starting server
2023-12-23 12:43:52,338 PM info  [database::migrations] establishing database connection
2023-12-23 12:43:52,338 PM info  [database::migrations] ensuring database exists, if not creating database - may error if no permissions
2023-12-23 12:43:57,175 PM debug [database::migrations] database is behind, attempting to migrate
2023-12-23 12:43:57,176 PM debug [database::migrations] migrating database
2023-12-23 12:43:57,968 PM error [database::migrations] failed to migrate database
2023-12-23 12:43:57,968 PM error [database::migrations] Failed to migrate database... exiting...
2023-12-23 12:43:57,969 PM error [database::migrations] Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `20210901024501_embed_image` migration started at 2023-12-21 03:17:10.493891 UTC failed

    at Object.<anonymous> (/home/container/node_modules/@prisma/migrate/dist/SchemaEngine.js:415:24)
    at SchemaEngine.handleResponse (/home/container/node_modules/@prisma/migrate/dist/SchemaEngine.js:256:36)
    at LineStream.<anonymous> (/home/container/node_modules/@prisma/migrate/dist/SchemaEngine.js:363:16)
    at LineStream.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream._pushBuffer (/home/container/node_modules/@prisma/migrate/dist/utils/byline.js:103:17)
    at LineStream._transform (/home/container/node_modules/@prisma/migrate/dist/utils/byline.js:97:8)
    at Transform._write (node:internal/streams/transform:175:8)
some sensitive info has been removed (I just removed random chunks where the info was)

**Comment by diced** [comment]
If possible connect to your postgres instance (it looks like its in supabase so there might be some web sql runner), and run the following query: `select * from "_prisma_migrations" where migration_name = '20210901024501_embed_image';` prisma should output logs to this and help us get a better picture to what went wrong

**Comment by KrazyKleb** [comment]
@diced 
```A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20210901024501_embed_image

Database error code: 42P01

Database error:
ERROR: relation "Image" does not exist

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"Image\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("namespace.c"), line: Some(433), routine: Some("RangeVarGetRelidExtended") }

   0: sql_schema_connector::apply_migration::apply_script
           with migration_name="20210901024501_embed_image"
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:106
   1: schema_core::commands::apply_migrations::Applying migration
           with migration_name="20210901024501_embed_image"
             at schema-engine/core/src/commands/apply_migrations.rs:91
   2: schema_core::state::ApplyMigrations
             at schema-engine/core/src/state.rs:201```

**Comment by KrazyKleb** [comment]
Also here's a screenshot
![image](https://github.com/diced/zipline/assets/124646709/7674e970-bbca-4f78-9bc1-1e1709abff13)

**Comment by KrazyKleb** [comment]
Bump (idk if this is how GitHub works)

**Comment by diced** [comment]
If you don't have any data stored, I'd recommend just resetting your database and letting Zipline run the migrations from the start again..

**Comment by diced** [comment]
Closing as stale, reopen if the suggestion above doesn't work.
