### ISSUE TITLE
Missing dependencies for setup.js [BUG]

### ISSUE THREAD

**Issue by louis-lau** [diced/zipline#59]
Installed nodejs (to my dismay, see #58 ) , did npm install to install dependencies, yet these were missing for setup.js:

```
❯ node setup.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/docker-compose/zipline/setup.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
```
❯ node setup.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'toml-patch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/docker-compose/zipline/setup.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by diced** [comment]
it should be fixed but make sure you `npm i ` or `yarn`
