### ISSUE TITLE
Setup.js: Wrong driver: "sqlite3" [BUG]

### ISSUE THREAD

**Issue by louis-lau** [diced/zipline#60]
```
(node:1) UnhandledPromiseRejectionWarning: MissingDriverError: Wrong driver: "sqlite3" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".
    at new MissingDriverError (/opt/zipline/node_modules/typeorm/error/MissingDriverError.js:10:28)
    at DriverFactory.create (/opt/zipline/node_modules/typeorm/driver/DriverFactory.js:67:23)
    at new Connection (/opt/zipline/node_modules/typeorm/connection/Connection.js:53:59)
    at ConnectionManager.create (/opt/zipline/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at /opt/zipline/node_modules/typeorm/index.js:195:66
    at step (/opt/zipline/node_modules/tslib/tslib.js:141:27)
    at Object.next (/opt/zipline/node_modules/tslib/tslib.js:122:57)
    at /opt/zipline/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/opt/zipline/node_modules/tslib/tslib.js:111:16)
```

setup.js is not filling in the right value for sqlite.

**Comment by diced** [comment]
fixed
