### ISSUE TITLE
Missing dependency: sqlite3 [BUG]

### ISSUE THREAD

**Issue by louis-lau** [diced/zipline#61]
```
(node:1) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/opt/zipline/node_modules/typeorm/error/DriverPackageNotInstalledError.js:10:28)
    at SqliteDriver.loadDependencies (/opt/zipline/node_modules/typeorm/driver/sqlite/SqliteDriver.js:127:19)
    at new SqliteDriver (/opt/zipline/node_modules/typeorm/driver/sqlite/SqliteDriver.js:28:15)
    at DriverFactory.create (/opt/zipline/node_modules/typeorm/driver/DriverFactory.js:43:24)
    at new Connection (/opt/zipline/node_modules/typeorm/connection/Connection.js:53:59)
    at ConnectionManager.create (/opt/zipline/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at /opt/zipline/node_modules/typeorm/index.js:195:66
    at step (/opt/zipline/node_modules/tslib/tslib.js:141:27)
    at Object.next (/opt/zipline/node_modules/tslib/tslib.js:122:57)
    at /opt/zipline/node_modules/tslib/tslib.js:115:75
```

Sqlite is offered as an option, but package.json doesn't have the right dependencies.

I really wanted to just quickly check this out, but I can only take so many issues before giving up. :(

**Comment by diced** [comment]
Package.json won't have the drivers that you want, please read https://zipline.diced.wtf/docs/config/getting-started#database on getting your prefered db drivers.

**Comment by louis-lau** [comment]
I see. I'm not used to having to install dependencies myself depending on the configuration. The way you've built the docker image also makes this impossible to do.

**Comment by diced** [comment]
I will be pushing a template docker-compose, but you will still have to create a config you can just copy this and change the values. https://zipline.diced.wtf/docs/config/example

**Comment by louis-lau** [comment]
Sure! Good to see an example config to copy. Also publishing to docker hub I hope? That way people deploying this using docker don't have to pull the source and build the image themselves.

What I meant by impossible was that none of those optional database dependencies are included in your dockerfile.

**Comment by diced** [comment]
yeah probably but it would be pretty weird to run

**Comment by louis-lau** [comment]
How so?

**Comment by diced** [comment]
sorry, forgot that I had a github action that builds docker images `docker pull docker.pkg.github.com/diced/zipline/zipline:next`

**Comment by louis-lau** [comment]
Ah, nice! Not really. I can just bindmount it in the docker-compose file.

```yaml
volumes:
  - ./Zipline.toml:/opt/zipline/Zipline.toml
```

This way I can use the prebuilt image. I can PR to update the docker-compose.

**Comment by diced** [comment]
O didn't even think about that, thanks!
