### ISSUE TITLE
[BUG] MariaDB Errors Out

### ISSUE THREAD

**Issue by TheRealHeyJack** [diced/zipline#63]
**Describe the bug**
MariaDB only creates one table then errors out with bellow Exibit A. the only table it creates is also bellow Exibit B 

**To Reproduce**
1. Use MariaDB or MySQL on Docker
2. Watch Container Die
3. Look at logs and see error

**Expected behavior**
MySQL/MariaDB to Work 

**Screenshots**
[Exibit A](https://media.discordapp.net/attachments/729771079224131717/817940045998587924/unknown.png)
[Exibit B](https://cdn.discordapp.com/attachments/729771079224131717/817941090636136448/unknown.png)

**Desktop (please complete the following information if desktop):**
 - OS: Debian 10
 - Browser: N/A
 - Zipline Version: 2.8.1

**Comment by nodgear** [comment]
Same issue, without docker container

**Comment by diced** [comment]
The newest commit 1745298f4770181298063acb75c7270b9cf2ec9c might fix this, please try it out!

**Comment by nodgear** [comment]
Does not fix for me, had to install postgres

**Comment by tzockt** [comment]
Same Problem with newest Version of zipline and Nodejs
- Ubuntu 20.04.2 LTS
- mysql  Ver 15.1 Distrib 10.3.29-MariaDB

```bash
zipline@stalin:~/zipline$ npm start

> zipline-next@2.9.0 start
> NODE_ENV=production node dist

/home/zipline/zipline/node_modules/typeorm/error/QueryFailedError.js:11
        var _this = _super.call(this) || this;
                           ^

QueryFailedError: ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT column 'id' used in key specification without a key length
    at new QueryFailedError (/home/zipline/zipline/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.<anonymous> (/home/zipline/zipline/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:216:45)
    at Query.<anonymous> (/home/zipline/zipline/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/zipline/zipline/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/zipline/zipline/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/zipline/zipline/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/zipline/zipline/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/zipline/zipline/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/zipline/zipline/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/zipline/zipline/node_modules/mysql/lib/protocol/Protocol.js:38:16) {
  code: 'ER_BLOB_KEY_WITHOUT_LENGTH',
  errno: 1170,
  sqlMessage: "BLOB/TEXT column 'id' used in key specification without a key length",
  sqlState: '42000',
  index: 0,
  sql: 'CREATE TABLE `zipline_data` (`id` text NOT NULL, `first` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (`id`)) ENGINE=InnoDB',
  query: 'CREATE TABLE `zipline_data` (`id` text NOT NULL, `first` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (`id`)) ENGINE=InnoDB',
  parameters: []
}
```

**Comment by diced** [comment]
This will be fixed in an upcoming release

**Comment by tzockt** [comment]
When comes the next version?

**Comment by rpxs** [comment]
zipline will be completely rewritten, so after the rewrite you'll see the new & improved zipline.

**Comment by diced** [comment]
> When comes the next version?

I can't give an exact estimate but core features will be ready to go in about a week or two. Then as I continue development old features from Zipline 2 will be sdded or removed as I see fit, but for sure this issue will be fixed.
