### ISSUE TITLE
[BUG] docker-compose failed

### ISSUE THREAD

**Issue by changchichung** [diced/zipline#72]
**Describe the bug**
docker-compose won't start

1. copy docker-compose template
```
cp docker-compose.template.yml docker-compose.yml
```
2. update expose ports
```
version: "3"
services:
  zipline:
    ports:
      - "87:8000"
    volumes:
      - "./uploads:/opt/zipline/uploads"
    build: .
    tty: true
```
3. docker-compose up -d
```
chchang@hqdc039:~/git/zipline$ docker-compose up -d
Creating network "zipline_default" with the default driver
Building zipline
Step 1/8 : FROM node:14
14: Pulling from library/node
76b8ef87096f: Pull complete
2e2bafe8a0f4: Pull complete
b53ce1fd2746: Pull complete
84a8c1bd5887: Pull complete
7a803dc0b40f: Pull complete
b800e94e7303: Pull complete
8e9f42962912: Pull complete
cc1c1f0d8c86: Pull complete
a42c31ab44dd: Pull complete
Digest: sha256:8eb45f4677c813ad08cef8522254640aa6a1800e75a9c213a0a651f6f3564189
Status: Downloaded newer image for node:14
 ---> d6602e31594f
Step 2/8 : WORKDIR /opt/zipline
 ---> Running in 8278610801e5
Removing intermediate container 8278610801e5
 ---> 75e703a95bc3
Step 3/8 : COPY . /opt/zipline
 ---> f479c232a4a0
Step 4/8 : RUN npm i
 ---> Running in 08036a204853
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> bcrypt@5.0.1 install /opt/zipline/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/opt/zipline/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote

> @ampproject/toolbox-optimizer@2.6.0 postinstall /opt/zipline/node_modules/@ampproject/toolbox-optimizer
> node lib/warmup.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
AMP OPTIMIZER Downloaded latest AMP runtime data.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1327 packages from 835 contributors and audited 1336 packages in 44.664s

91 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (4 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 08036a204853
 ---> 56150b05dbdc
Step 5/8 : RUN npm run build
 ---> Running in 3956ca9860ba

> zipline-next@2.9.0 build /opt/zipline
> next build && tsc -p .

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
info  - Creating an optimized production build...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/11)
info  - Generating static pages (2/11)
info  - Generating static pages (5/11)
info  - Generating static pages (8/11)
info  - Generating static pages (11/11)
info  - Finalizing page optimization...

Page                                                           Size     First Load JS
┌ ○ /                                                          239 B          99.1 kB
├   /_app                                                      0 B            98.8 kB
├ ○ /404                                                       5.48 kB         104 kB
├ ● /dash                                                      1.05 kB         357 kB
├ ● /dash/images                                               4.28 kB         360 kB
├ ○ /dash/statistics                                           2.44 kB         356 kB
├ ○ /dash/upload                                               15.4 kB         369 kB
├ ● /dash/urls                                                 2.94 kB         360 kB
├ ○ /dash/users                                                4.45 kB         362 kB
├ ○ /user/login                                                4.33 kB         132 kB
├ ● /user/manage                                               2.18 kB         360 kB
└ ○ /user/setup                                                2.46 kB         130 kB
+ First Load JS shared by all                                  98.8 kB
  ├ chunks/54d8afaa53b3f96daaf95af2d599c4ace7023576.c2f253.js  26 kB
  ├ chunks/8af701fd6c717923a0d81eba7532ee453c4f3efd.13981a.js  9.76 kB
  ├ chunks/990404156a8317c8d69269cd1922f67953c7c0f0.223f05.js  11.1 kB
  ├ chunks/framework.13d6f2.js                                 40.2 kB
  ├ chunks/main.4aa302.js                                      7.19 kB
  ├ chunks/pages/_app.7d0c9c.js                                3.91 kB
  └ chunks/webpack.e06743.js                                   751 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

Removing intermediate container 3956ca9860ba
 ---> bbe23839168f
Step 6/8 : ENV NODE_ENV=production
 ---> Running in e75681ef027c
Removing intermediate container e75681ef027c
 ---> ed24a4582f9c
Step 7/8 : EXPOSE 8000
 ---> Running in 2bbddab9bcde
Removing intermediate container 2bbddab9bcde
 ---> 15c7b05270bc
Step 8/8 : CMD ["node", "dist"]
 ---> Running in 520b412778c3
Removing intermediate container 520b412778c3
 ---> 7774233226dd
Successfully built 7774233226dd
Successfully tagged zipline_zipline:latest
WARNING: Image for service zipline was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating zipline_zipline_1 ... done
```

docker status
```
chchang@hqdc039:~/git/zipline$ docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS                            NAMES
e8a68b08a638        zipline_zipline                 "docker-entrypoint.s…"   2 minutes ago       Exited (0) 2 minutes ago                                     zipline_zipline_1
```

docker logs
```
chchang@hqdc039:~/git/zipline$ docker logs zipline_zipline_1 
[4/20/2021 3:09:11 AM] [configuration] error: could not find a Zipline.toml file in /opt/zipline
```

**Comment by diced** [comment]
You need to create a Zipline.toml (you can use an example one from https://zipline.diced.wtf/docs/config/example/)

**Comment by changchichung** [comment]
can I generate Zipline.toml without install by ```npm i ``` ?
for example , I want to use sqllite as DB backend . but I dont know what's exactlly the syntax in config.

**Comment by changchichung** [comment]
so , after all , I still run npm i to install node_modules to do auto setup.
and here is the Zipline.toml
```
[database]
type = "sqlite"
host = ""
port = NaN
database = "./"
username = ""
password = ""

[meta]
title = "Zipline"
description = "My Zipline Server"
thumbnail = "https://github.githubassets.com/images/modules/open_graph/github-mark.png"
color = "#128377"

[core]
secret = "password"
port = 87
host = "0.0.0.0"
theme = "dark"
secure = false
mfa = false

[uploader]
directory = "data"
route = "/u"
length = 6
original = true
blacklisted = []

[urls]
route = "/go"
length = 4
vanity = true
```
and docker-compose.yml
```
version: "3"
services:
  zipline:
    ports:
      - "87:87"
    volumes:
      - "/home/chchang/git/zipline/data:/opt/zipline/data"
    build: .
    tty: true
```

but docker still exited.
```
chchang@hqdc039:~/git/zipline$ docker logs zipline_zipline_1 
(node:1) UnhandledPromiseRejectionWarning: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/opt/zipline/node_modules/typeorm/error/DriverPackageNotInstalledError.js:11:28)
    at SqliteDriver.loadDependencies (/opt/zipline/node_modules/typeorm/driver/sqlite/SqliteDriver.js:128:19)
    at new SqliteDriver (/opt/zipline/node_modules/typeorm/driver/sqlite/SqliteDriver.js:29:15)
    at DriverFactory.create (/opt/zipline/node_modules/typeorm/driver/DriverFactory.js:44:24)
    at new Connection (/opt/zipline/node_modules/typeorm/connection/Connection.js:54:59)
    at ConnectionManager.create (/opt/zipline/node_modules/typeorm/connection/ConnectionManager.js:57:26)
    at /opt/zipline/node_modules/typeorm/index.js:219:66
    at step (/opt/zipline/node_modules/tslib/tslib.js:143:27)
    at Object.next (/opt/zipline/node_modules/tslib/tslib.js:124:57)
    at /opt/zipline/node_modules/tslib/tslib.js:117:75
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
chchang@hqdc039:~/git/zipline$ 
```

**Comment by diced** [comment]
> can I generate Zipline.toml without install by `npm i ` ?
> for example , I want to use sqllite as DB backend . but I dont know what's exactlly the syntax in config.
yes that's why I pointed towards the example config.
