### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by toddhow** [diced/zipline#81]
I'm getting this error when I try to build 

```
npm run build

> zip3@3.0.0 build /root/zipline
> npm-run-all build:schema build:next


> zip3@3.0.0 build:schema /root/zipline
> prisma generate --schema=prisma/schema.shared.prisma

Prisma schema loaded from prisma/schema.shared.prisma

✔ Generated Prisma Client (2.25.0) to ./node_modules/@prisma/client in 168ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

> zip3@3.0.0 build:next /root/zipline
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Failed to compile.


./src/pages/auth/login.tsx:3:10

Type error: Module '"@material-ui/core/Alert/Alert"' has no exported member 'Color'. Did you mean to use 'import Color from "@material-ui/core/Alert/Alert"' instead?

  1 | import React, { useEffect, useState } from 'react';
  2 | import { Typography, Box, TextField, Stack, Button } from '@material-ui/core';
> 3 | import { Color } from '@material-ui/core/Alert/Alert';
    |          ^
  4 | import { useRouter } from 'next/router';
  5 | import Alert from 'components/Alert';
  6 | import Backdrop from 'components/Backdrop';
```

**Comment by toddhow** [comment]
Here is some more of the errors

```

info  - Checking validity of types .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zip3@3.0.0 build:next: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zip3@3.0.0 build:next script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-19T20_36_51_040Z-debug.log
ERROR: "build:next" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zip3@3.0.0 build: `npm-run-all build:schema build:next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zip3@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by toddhow** [comment]
Heres the debug log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/.nvm/versions/node/v14.17.3/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v14.17.3/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:next'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'prebuild:next', 'build:next', 'postbuild:next' ]
5 info lifecycle zip3@3.0.0~prebuild:next: zip3@3.0.0
6 info lifecycle zip3@3.0.0~build:next: zip3@3.0.0
7 verbose lifecycle zip3@3.0.0~build:next: unsafe-perm in lifecycle true
8 verbose lifecycle zip3@3.0.0~build:next: PATH: /root/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/zipline/node_modules/.bin:/root/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/zipline/node_modules/.bin:/root/.nvm/versions/node/v14.17.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle zip3@3.0.0~build:next: CWD: /root/zipline
10 silly lifecycle zip3@3.0.0~build:next: Args: [ '-c', 'next build' ]
11 silly lifecycle zip3@3.0.0~build:next: Returned: code: 1  signal: null
12 info lifecycle zip3@3.0.0~build:next: Failed to exec build:next script
13 verbose stack Error: zip3@3.0.0 build:next: `next build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid zip3@3.0.0
15 verbose cwd /root/zipline
16 verbose Linux 5.4.0-29-generic
17 verbose argv "/root/.nvm/versions/node/v14.17.3/bin/node" "/root/.nvm/versions/node/v14.17.3/lib/node_modules/npm/bin/npm-cli.js" "run" "build:next"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error zip3@3.0.0 build:next: `next build`
22 error Exit status 1
23 error Failed at the zip3@3.0.0 build:next script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by diced** [comment]
not able to recreate make sure you are on latest node and maybe try git cloning again..
